@host=http://localhost:5235
GET {{host}}/turqoise
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4ZWZmNjY4NS00ZDQ2LTQxZTktODZhZC1mNmQyODMzMmE5ZDgiLCJnaXZlbl9uYW1lIjoicmFtYXphbiIsImZhbWlseV9uYW1lIjoiZ29sZGVuaGlsbCIsImp0aSI6ImE3ODQ5YzU4LWE1YTEtNDY4ZS04ODRlLWQ3MTc3OWYxZmYxZCIsImV4cCI6MTc0MjE0NjgxMywiaXNzIjoiVHVycW9pc2VFYXRhcnkiLCJhdWQiOiJUdXJxb2lzZUVhdGFyeSJ9.7xBZp4Z6C3s_GUsNc8p1IR60v-JlAKEhCg4KOCBYfqo