@host=http://localhost:5235
GET {{host}}/turqoise
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3YzUzMWE4Mi1jOTRkLTQ5OWEtODRlNS1kMTJhNmUwM2M4ZWUiLCJnaXZlbl9uYW1lIjoicmFtYXphbiIsImZhbWlseV9uYW1lIjoiZ29sZGVuaGlsbCIsImVtYWlsIjoicmFtYXphbjZAY3JhemJveS5jb20iLCJqdGkiOiIzY2UyZDQwNC00NGFiLTQ1ZGMtYTE3My05MmYxZDYzYmRhY2YiLCJleHAiOjE3NDMxNTE2MzUsImlzcyI6IlR1cnFvaXNlRWF0YXJ5IiwiYXVkIjoiVHVycW9pc2VFYXRhcnkifQ.9PQmsHsJPm0U4SXYz-saIAwYBtpTr0kaJF5E1bCmbvY