@host=http://localhost:5235

POST http://localhost:5235/auth/register
Content-Type: application/json

{
    "firstName":"",
    "lastName":"",
    "email":"ramazan@crazboy.com",
    "password":"ramazan123"
}