@host=http://localhost:5235
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyMjNlOWVkNC0xZWYxLTQzM2MtOGUxMS1mZGNmY2E4OTViMTEiLCJnaXZlbl9uYW1lIjoicmFtYXphbiIsImZhbWlseV9uYW1lIjoiZ29sZGVuaGlsbCIsImVtYWlsIjoicmFtYXphbjRAY3JhemJveS5jb20iLCJqdGkiOiIzMTAyOGM5ZC03OTUyLTQ3NzctYWUyYi00ODhiMTkyODcxNGEiLCJleHAiOjE3NDMxNTA1NjQsImlzcyI6IlR1cnFvaXNlRWF0YXJ5IiwiYXVkIjoiVHVycW9pc2VFYXRhcnkifQ.YRZ0XkSQjU3IRPti0875ZCkmo1IPeJQ0CvsBcpHq7R4
GET {{host}}/auth/test-auth
Authorization: Bearer {{token}}